### ISSUE TITLE
undefined method `elements' for nil:NilClass 

### ISSUE THREAD

**Issue by noctivityinc** [chrisyour/geo_location#3]
When running GeoLocation.find('127.0.0.1') I get the following error:

```
undefined method `elements' for nil:NilClass 
```

and here is the trace...

```
activesupport (3.0.3) lib/active_support/whiny_nil.rb:48:in `method_missing'
geo_location (0.4.0) lib/geo_location/geo_location.rb:109:in `data_from_hostip_http_response'
geo_location (0.4.0) lib/geo_location/geo_location.rb:64:in `hostip'
geo_location (0.4.0) lib/geo_location/geo_location.rb:12:in `find'
```

**Comment by chrisyour** [comment]
Hi there,

Are you using HostIP for your service or MaxMind? Also, we've pushed a couple updates to GitHub (but not the official gem yet). Try including the GitHub url in your Gemspec file and 'bundle install'. Do you still get the same error?

Let me know.

Chris

**Comment by noctivityinc** [comment]
Yeah that did it.  Im using HostIP and just used your github gem and it works 100%:

```
ruby-1.9.2-p136 :002 > GeoLocation.find('127.0.0.1')
 => {:city=>"(Private Address)", :region=>nil, :country_code=>"XX", :country=>nil, :ip=>"127.0.0.1", :timezone=>nil} 
```

Thanks,

J

**Comment by chrisyour** [comment]
Perfect. I've pushed up a new version (0.4.1) to RubyGems, so you don't have to specify the Git repository anymore.

Thanks,
Chris
